# Generated by Django 5.1.4 on 2025-01-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblSubTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTopMenuName', models.CharField(max_length=200, null=True)),
                ('subTopMenuImage', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topMenuName', models.CharField(max_length=200, null=True)),
                ('topMenuImage', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblSub2TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub2TopMenuName', models.CharField(max_length=200, null=True)),
                ('sub2TopMenuImage', models.CharField(max_length=200, null=True)),
                ('subTopMenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblsubtopmenu')),
            ],
        ),
        migrations.AddField(
            model_name='tblsubtopmenu',
            name='TopMenuID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tbltopmenu'),
        ),
    ]
