# Generated by Django 5.1.2 on 2025-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_tblproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutUsName', models.CharField(max_length=200, null=True)),
                ('aboutUsImage', models.ImageField(upload_to='ProductImages/')),
                ('videoImage', models.ImageField(upload_to='ProductImages/')),
                ('phoneNumber', models.IntegerField(max_length=15, null=True)),
                ('advan1', models.CharField(max_length=200, null=True)),
                ('advan2', models.CharField(max_length=200, null=True)),
                ('advan3', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
