# Generated by Django 5.1.2 on 2025-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tblaboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblaboutus',
            name='aboutUsImage',
            field=models.ImageField(upload_to='AboutUsImages/'),
        ),
        migrations.AlterField(
            model_name='tblaboutus',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblaboutus',
            name='videoImage',
            field=models.ImageField(upload_to='AboutUsImages/'),
        ),
    ]
