# Generated by Django 5.1.2 on 2025-01-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tblfoodmenu_delete_tblproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblfoodmenu',
            old_name='productDate',
            new_name='foodDate',
        ),
        migrations.RenameField(
            model_name='tblfoodmenu',
            old_name='productImage',
            new_name='foodImage',
        ),
    ]
