# Generated by Django 5.1.4 on 2025-01-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tblenventcatalog_tblaboutus_aboutdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblfoodmenu',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tblfoodmenu',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
