# Generated by Django 5.1.2 on 2025-01-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_tblfoodmenu_quantity_category_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblBookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('bookDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookTime', models.TimeField(auto_now_add=True, null=True)),
                ('noPeople', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
