# Generated by Django 5.1.2 on 2025-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tblbooktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideTitle', models.CharField(max_length=200, null=True)),
                ('slideDescription', models.CharField(max_length=200, null=True)),
                ('slideImage', models.ImageField(upload_to='SlideImages/')),
                ('status', models.IntegerField(max_length=1, null=True)),
            ],
        ),
    ]
