# Generated by Django 5.1.2 on 2025-01-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_tblslide_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooktable',
            name='bookDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
