# Generated by Django 5.1.2 on 2025-01-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tblbooktable_bookdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbooktable',
            name='bookDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tblbooktable',
            name='bookTime',
            field=models.TimeField(null=True),
        ),
    ]
