# Generated by Django 5.1.5 on 2025-01-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_tblfoodmenu_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefName', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('chefDescription', models.CharField(max_length=200, null=True)),
                ('chefImage', models.ImageField(upload_to='SlideImages/')),
            ],
        ),
        migrations.AlterField(
            model_name='tblfoodmenu',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
