# Generated by Django 5.1.5 on 2025-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tblchef_alter_tblfoodmenu_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsubtopmenu',
            name='TopMenuID',
        ),
        migrations.AlterField(
            model_name='tblfoodmenu',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.DeleteModel(
            name='tblSub2TopMenu',
        ),
        migrations.DeleteModel(
            name='tblSubTopMenu',
        ),
    ]
