# Generated by Django 5.1.5 on 2025-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_tblsubtopmenu_topmenuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='GalleryImages/')),
            ],
        ),
        migrations.AlterField(
            model_name='tblchef',
            name='chefImage',
            field=models.ImageField(upload_to='ChefImages/'),
        ),
    ]
