# Generated by Django 5.1.5 on 2025-01-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tblgallery_alter_tblchef_chefimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblgallery',
            name='ImageName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
