# Generated by Django 5.1.5 on 2025-01-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_tblgallery_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblslide',
            name='slideDescription',
        ),
        migrations.RemoveField(
            model_name='tblslide',
            name='slideTitle',
        ),
        migrations.RemoveField(
            model_name='tblslide',
            name='status',
        ),
        migrations.AddField(
            model_name='tblslide',
            name='button_link',
            field=models.CharField(default='#book-a-table', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='tblslide',
            name='button_text',
            field=models.CharField(default='Book a Table', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='tblslide',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblslide',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tblslide',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblslide',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
