# Generated by Django 5.1.5 on 2025-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_tblslide_slidedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltopmenu',
            name='topMenuLink',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
