# Generated by Django 5.1.2 on 2025-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tblwhyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblwhyus',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
