# Generated by Django 5.1.2 on 2025-02-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_aboutusname_tblaboutus_advan4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblaboutus',
            old_name='advan4',
            new_name='aboutUsName',
        ),
        migrations.RemoveField(
            model_name='tblaboutus',
            name='introduction',
        ),
    ]
