# Generated by Django 5.1.2 on 2025-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_advan4_tblaboutus_aboutusname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblaboutus',
            name='advan4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
